[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<main.cpp>

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.11
  adafruit/Adafruit SSD1306 @ ^2.5.11
  sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
  adafruit/Adafruit MLX90614 Library @ ^2.1.5

[env:mlx90614-oled-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<mlx90614_oled_test.cpp>

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.11
  adafruit/Adafruit SSD1306 @ ^2.5.11
  adafruit/Adafruit MLX90614 Library @ ^2.1.5

[env:mlx90614-quick-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<mlx90614_quick_test.cpp>

lib_deps =
  adafruit/Adafruit MLX90614 Library @ ^2.1.5

[env:mpu6050-oled-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<mpu6050_oled_test.cpp>

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.11
  adafruit/Adafruit SSD1306 @ ^2.5.11

[env:max98357-speaker-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<max98357_speaker_test.cpp>

[env:inmp441-i2s-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<inmp441_i2s_test.cpp>

[env:voice-backend-text-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<voice_backend_text_test.cpp>

lib_deps =
  gilmaimon/ArduinoWebsockets @ ^0.5.4
  bblanchon/ArduinoJson @ ^7.4.1

[env:voice-backend-live-test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<voice_backend_live_test.cpp>

lib_deps =
  gilmaimon/ArduinoWebsockets @ ^0.5.4
  bblanchon/ArduinoJson @ ^7.4.1
